### ISSUE TITLE
Is there a known working combination of arduino_tinyusb and tinyusb that works for v3.0.x?

### ISSUE THREAD

**Issue by elliotmatson** [Jason2866/Arduino_IDF_TinyUSB#1]
I'm working on getting a project migrated to pioarduino/platform-espressif32 so I can use later versions of ESP-IDF/Arduino, but I'm having a hard time finding a working config. Where did the version of tinyusb used in this repo come from originally?

**Comment by Jason2866** [comment]
The source is https://github.com/espressif/esp32-arduino-lib-builder/tree/release/v4.4/components/arduino_tinyusb

For core 3.x.x use https://github.com/espressif/esp32-arduino-lib-builder/tree/release/v5.3/components/arduino_tinyusb

**Comment by Jason2866** [comment]
And clone (**NOT** recursive this repo https://github.com/hathach/tinyusb.git
See https://github.com/espressif/esp32-arduino-lib-builder/blob/release/v5.3/tools/update-components.sh

**Comment by elliotmatson** [comment]
Thanks so much! I don't know why, but I had assumed this used the espressif fork of tinyusb
